version: '3.9'

services:
  homebase.ts.api:
    image: homebase.ts.api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env.production
    ports:
      - 8080:8080
    links:
        - "db"
      
  db:
    image: mongo
    ports:
        - "27017:27017"
    volumes:
        - db-data:/data/db

volumes:
   db-data:
    external: true
